### ISSUE TITLE
not recognized as an internal or external command

### ISSUE THREAD

**Issue by Ponita0** [ElDavoo/wa-crypt-tools#113]
this is not actually a can't decrypt issue. 
My cmd can't even find the script file
i tried .exe to but it's just not there
`'decrypt14_15.exe' is not recognized as an internal or external command,
operable program or batch file.`
tried powershell too 
`decrypt14_15 : The term 'decrypt14_15.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.`
I did every step correctly.

**Comment by Ponita0** [comment]
![image](https://github.com/ElDavoo/wa-crypt-tools/assets/34416796/ac43e7c9-aa92-4476-ab60-4b0c8b628aae)

**Comment by ElDavoo** [comment]
Hi,
for the time being, please use pip:
`python -m pip install wa-crypt-tools`

**Comment by Ponita0** [comment]
this was indeed the first step 
`
D:\whatsappDecrypt>python -m pip install wa-crypt-tools
Requirement already satisfied: wa-crypt-tools in c:\users\3frak\appdata\local\programs\python\python311\lib\site-packages (0.0.8)
Collecting javaobj-py3@ git+https://github.com/tcalmant/python-javaobj@fba64e9 (from wa-crypt-tools)
  Cloning https://github.com/tcalmant/python-javaobj (to revision fba64e9) to c:\users\3frak\appdata\local\temp\pip-install-_9r3vwdp\javaobj-py3_834a1cd999bc4e8ea6b67fe3b7b5eb24
  Running command git clone --filter=blob:none --quiet https://github.com/tcalmant/python-javaobj 'C:\Users\3frak\AppData\Local\Temp\pip-install-_9r3vwdp\javaobj-py3_834a1cd999bc4e8ea6b67fe3b7b5eb24'
  WARNING: Did not find branch or tag 'fba64e9', assuming revision or ref.
  Running command git checkout -q fba64e9
  Resolved https://github.com/tcalmant/python-javaobj to commit fba64e9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pycryptodomex~=3.18 in c:\users\3frak\appdata\local\programs\python\python311\lib\site-packages (from wa-crypt-tools) (3.20.0)
Requirement already satisfied: protobuf<4.26.0,>=4.24.1 in c:\users\3frak\appdata\local\programs\python\python311\lib\site-packages (from wa-crypt-tools) (4.25.3)

`

**Comment by roshaniaher** [comment]
getting the Same error  even with 

`python -m pip install wa-crypt-tools`

'decrypt14_15' is not recognized as an internal or external command,
operable program or batch file.

**Comment by roshaniaher** [comment]
I have pasted all the db an key files in the wa-crypt-tools folder, is this right way?

**Comment by aldennisa15** [comment]
The `README` is just a little out of date. The decode script was renamed from `decrypt14_15` to `wadecrypt` (see [this commit](https://github.com/ElDavoo/wa-crypt-tools/commit/1a8cc9e6aafd79b6992a49156ef95be09f59d5ae#diff-64e5dc08b9ac956d95fc26c9266a0b8d90cbc05e9db156121c13255d7460aa40)).

Try that command instead. (I've no doubt the README will get updated in due course.)

**Comment by ElDavoo** [comment]
> The `README` is just a little out of date. The decode script was renamed from `decrypt14_15` to `wadecrypt` (see [this commit](https://github.com/ElDavoo/wa-crypt-tools/commit/1a8cc9e6aafd79b6992a49156ef95be09f59d5ae#diff-64e5dc08b9ac956d95fc26c9266a0b8d90cbc05e9db156121c13255d7460aa40)).
> 
> Try that command instead. (I've no doubt the README will get updated in due course.)

Hmmm I probably got confused with which commit I released in pip (?)
