### ISSUE TITLE
ElDavoo wa-crypt-tool Discord?

### ISSUE THREAD

**Issue by russandro** [ElDavoo/wa-crypt-tools#134]
Is a discord for this project ever gonna be created?
I think it would be really helpful, even for times someone need help and maybe wants it faster than rather submitting an issue through GitHub (like in my case).

**Comment by russandro** [comment]
_P.S._
I really am a fan of this and whoa tool-kit project.
About this one, the question in particular was referred to how, or if, I could use a key 64 digits (took from encrypting a db in E2E encryption) and use it for the others db.crypt.14 databases I got in my phone).

**Comment by ElDavoo** [comment]
Hi, I don't think a support community is a very good idea:
- The project is (supposed to be! 😀) simple to use and efficient 
- There aren't a lot of features to be developed 
- It would take people to ask me always the same questions (e.g. "can I decrypt this DB without the key?")

Obviously I can change my mind if there is enough demand.

About your other question, yes, the stickers, chat settings should decrypt just fine.

**Comment by russandro** [comment]
Thanks for the answer 🙏🏽🤝😊

**Comment by ElDavoo** [comment]
There are always GitHub discussions :)
