### ISSUE TITLE
wa.db.crypt15 empty

### ISSUE THREAD

**Issue by riekusr** [ElDavoo/wa-crypt-tools#136]
This tool is working excellent for the msgstore. I use the same command to decrypt the wa database to get the contacts. That works but the database is empty, it does have the tables.

Any suggestions? The file is 21kb. 
Tried several times reinstall whatsapp and run new backups

**Comment by ElDavoo** [comment]
I don't know. This project is about decrypting/encrypting, the contents of the file are out of scope.
I just tried decrypting my wa.db.crypt15 and it does contain something. Maybe you need to give contact permission and wait for it to sync.
