### ISSUE TITLE
wacreatekey bug with crypt14 PLUS solution

### ISSUE THREAD

**Issue by code-consensus** [ElDavoo/wa-crypt-tools#140]
Hi,

I noticed a bug in using wacreatekey to make a crypt14 key, but I also have found the solution. However, I have never made any contributions before to github code, so I don't know how to make suggested changes directly to @ElDavoo's code, but I will outline the problem and solution here.

As per the help (wacreatekey -h), you can create a crypt14 key as follows, optionally specifying the server salt (64-digit hex number) and googleid salt (32-digit hex number):
`wacreatekey --crypt14 --server-salt SERVER_SALT --googleid GOOGLEID`

Try either of these options on the command-line and you will get an invalid length error, e.g.:
`wacreatekey --crypt14 --server-salt 1234567890123456789012345678901234567890123456789012345678901234` gives an error of "Invalid server salt length"
_and_ 
`wacreatekey --crypt14 --googleid 12345678901234567890123456789012` gives an error of "Invalid google id length"

The issue lies in wacreatekey.py under the "if args.crypt14:" section, line 70, and how it calls the Key14 class:
`key: Key14 = Key14(cipher_version=args.cipher_version.to_bytes(2, "big"), key_version=args.key_version.to_bytes(1, "big"), serversalt=args.server_salt, googleid=args.googleid, iv=None, key=None)`, specifically the items **serversalt=args.server_salt, googleid=args.googleid**

According to key14.py, the Key14 class expects bytes, but it is being passed _strings_ in wacreatekey.py. Changing the code around the sever_salt and googleid fixes the problem:
_serversalt=**int(args.server_salt, 16).to_bytes(32, "big")**, googleid=**int(args.googleid, 16).to_bytes(16, "big")**_
i.e. the full line would now be:
`key: Key14 = Key14(cipher_version=args.cipher_version.to_bytes(2, "big"), key_version=args.key_version.to_bytes(1, "big"), serversalt=int(args.server_salt, 16).to_bytes(32, "big"), googleid=int(args.googleid, 16).to_bytes(16, "big"), iv=None, key=None)`

N.B. cipher_version and key_version are unaffected, given that they are either 0 or 1 in the case of cipher, and 1, 2 or 3 for key_version, but if those were to be larger hex numbers in the future, then the code around them many need to also change.

Related to **key version**, for which supported numbers are 1, 2 or 3 (default) -- I see that the key version has gone up all the way to 32 in newer WhatsApp installations. Is there any plan to add newer key versions to the algorithm?

Also, with regard to the way wacreatekey calls Key14, why does it only create a random key (passes key=None), versus potentially passing a user-specified key with --hex?

@ElDavoo thanks for the amazing work on these scripts -- this has been an absolute lifesaver in recovering my message data!!

**Comment by ElDavoo** [comment]
Wow, amazing job!

> Related to **key version**, for which supported numbers are 1, 2 or 3 (default) -- I see that the key version has gone up all the way to 32 in newer WhatsApp installations. Is there any plan to add newer key versions to the algorithm?

Good to know! I arbitrarily named this field "key version", but I didn't actually know what does it do. From what you said it's more like a key ID rather than "version" (so it gets incremented at each change). I will change the checks so the only thing that will be checked is if the key ID in the key and in the encrypted file matches.  

> Also, with regard to the way wacreatekey calls Key14, why does it only create a random key (passes key=None), versus potentially passing a user-specified key with --hex?

Sigh. These tools were a little bit rushed out (untested). This afternoon I will be inside a train for a few hours, I will try to make some new tests about key14 creation, and then to fix the code as you said.

**Comment by ElDavoo** [comment]
I think I wrote tests for and fixed all the bugs mentioned here, so I will close as completed. Feel free to open more issues as you find more bugs. I only worked on wacreatekey, other tools (except wadecrypt) are largely untested and left to the user's guesswork.

> However, I have never made any contributions before to github code, so I don't know how to make suggested changes directly to @ElDavoo's code, but I will outline the problem and solution here.

In order to do that you need to learn how to make a [pull request.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

**Comment by code-consensus** [comment]
> maybe it's a bug in there?

Well, one thing that I _did_ notice in the code is that, in waencrypt, as it calls the functions from db14.py, and there you are actually _always_ setting the database Key Version to 32 when encrypting the database. 

From the encrypt() function in db14.py:
`cipher.key_version = "2".encode()` -- i.e. "2" is ASCII character 50 or hexadecimal _32_
But then you also have a "#FIXME" above it, and I'm not sure if that is related to cipher.key_version or not.

Is it because all crypt14 files have a key_version of 32? 

N.B. in db14.py under Database14(Database), you also have a large section commented out that makes reference to the key_version of the key and the key_version of the database, and specifically that would reject key_version differences between the key and the database. But again -- see my comment above that you can still decrypt with different key_versions anyway.

So as for wainfo if there is a bug, I looked at the code. I can see that it calls header_info() from utils.py, and there it _is_ pulling out the the database's key_version:
line 170: `header.c14_cipher.key_version.hex())`

What I can't understand (I don't understand protobuf), is how header.c14_cipher.key_version is getting the key_version -- I guess this is somehow pulling from **backup_prefix_pb2.py** or **C14_cipher_pb2.py**? What I can't tell from those files, is whether it is legitimately pulling out the key_version, or is it just defaulting it at 32?

**Comment by code-consensus** [comment]
I did some further testing, which I think is instructive.

I did as follows:

1. I took an encrypted crypt14 database (with key_version shown as "32" with wainfo), and its decryption key (exported from the phone) with a key_version listed as "3" as per wainfo.
2. I decrypted the crypt14 database with **wadecrypt** (the new version @ElDavoo posted on github, not v0.1.0), and noted all the crypt14 database details (IV, whatsapp version, phone number jid backup version, features list, and max feature number).
3. The decryption was successful, and I could view the database, let's call it "msgstore.db".
4. I then _re-encrypted_ the msgstore.db with crypt14 using **waencrypt**, specifying every command-line option to match the originally encrypted database file, resulting in msgstore_reencrypted.db.crypt14
5. I then create a _NEW_ crypt14 key using **wacreatekey** (the new version @ElDavoo posted on github, not v0.1.0), using the _same_ hash as the original decryption key, _same_ server-salt, _same_ googleid, but _**different** key_version_ -- instead of "3", I changed it to "**_1_**".
6. Then as in step 4 above, I take this altered key with key_version 1 and I encrypt msgstore.db, specifying every command-line option to match the original database, resulting in msgstore_altered_key_version.db.crypt14.

**The result?**
The _original_ msgstore.db.crypt14, msgtore_reencrypted.db.crypt14, **_and_** msgstore_altered_key_version.db.crypt14 _ALL_  resulted in the **exact same SHA256 hash**.

> maybe it's a bug in there?

Clearly this means that there is **no relevant connection** between the key_version of the _decryption key_ and the key_version of the _crypt14 database_. I [noted above](https://github.com/ElDavoo/wa-crypt-tools/issues/140#issuecomment-2346301233) commented out sections the code that would have caused the program to exit if key_versions where different -- clearly that should stay commented out.

So, from what I gather above, regardless of whether wainfo is showing correct info on the key_version of crypt14 databases, the end-result is that **wadecrypt** and **waencrypt** **_are working correctly_ with crypt14**!
