### ISSUE TITLE
msgstore.db.crypt15 contains more data than a DB File

### ISSUE THREAD

**Issue by 3llomi** [ElDavoo/wa-crypt-tools#158]
I noticed that msgstore.db (after decryption) is containing more data than a DB or SQLite file.
I tried to run binwalk against it and it outputs a lot of addresses

![CleanShot 2024-12-26 at 17 09 22](https://github.com/user-attachments/assets/7bcd08b0-4e36-4932-9ba3-2576055a5a6e)

I ran `binwalk --dd="jpeg:jpg" msgstore.db` and I was able to extract thumbnails of the images as well. but for some reason each image is about 30MB - I guess it has scrambled data within?

I guess we can get more data out of msgstore.db after decryption? perhaps stickers database?

**Comment by ElDavoo** [comment]
They're just inside the database.

Stickers are in their own separate backup.
