### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by xOldeVx** [ElDavoo/wa-crypt-tools#73]
I installed **wa-crypt-tools** with `python -m pip install wa-crypt-tools` command
After this when I run `decrypt14_15 ./encrypted_backup.key ./msgstore.db.crypt15 ./msgstore.db` i'm getting error `zsh: command not found: decrypt14_15`

Using Mac M1

**Comment by ElDavoo** [comment]
It's working on my friend's laptop, but he also has anaconda installed.
<img width="1170" alt="Screenshot 2023-07-06 at 08 05 45" src="https://github.com/ElDavoo/wa-crypt-tools/assets/7345120/6877b74e-2ac7-4144-a519-aff2f2c22aad">

**Comment by ElDavoo** [comment]
Yep, but they don't always work. I suggest you to search on github for projects that can get the key file.

**Comment by nabil-el-houssein** [comment]
How did you solve this? I followed the instructions and I'm still getting this error. https://i.imgur.com/1QdE8sw.png

**Comment by ElDavoo** [comment]
> How did you solve this? I followed the instructions and I'm still getting this error. https://i.imgur.com/1QdE8sw.png

hi, in the development version the tool is named wadecrypt

**Comment by nabil-el-houssein** [comment]
This is it. Thank you.
