### ISSUE TITLE
msgstore.db file is gibberish

### ISSUE THREAD

**Issue by xOldeVx** [ElDavoo/wa-crypt-tools#75]
I received a file named `msgstore.db` by running `decrypt14_15 ./encrypted_backup.key ./msgstore.db.crypt15 ./msgstore.db` commend, but the exported file is gibberish, what's wrong?

Here's 2 screenshots
![image](https://github.com/ElDavoo/wa-crypt-tools/assets/24361103/79729e5c-0002-4d6e-b8ac-1b7638343ad9)
![image](https://github.com/ElDavoo/wa-crypt-tools/assets/24361103/c65fe445-a008-4870-b423-1e704c974682)

**Comment by aldennisa15** [comment]
As it says right at the start, the file is an SQLite file (https://en.wikipedia.org/wiki/SQLite), not gibberish

**Comment by ElDavoo** [comment]
Hi,
As the file is an SQLite file, you need to read it using the SQLite command line program or some SQLite GUI.
