### ISSUE TITLE
Decryp msgstore.db.crypt15 with password possible ?

### ISSUE THREAD

**Issue by MythB** [ElDavoo/wa-crypt-tools#77]
Hello, is it possible to decrypt `msgstore.db.crypt15` file with custom password? I have drive backup files. I am not sure what my password is, I have already tried 5 times via whatsapp. I need to try my possible passwords offline to be able to restore my drive backup.

**Comment by ElDavoo** [comment]
Hi,
no, the password is used to fetch the actual key from the server.
