### ISSUE TITLE
hex encoded string of Encrypted_backup.key generator util

### ISSUE THREAD

**Issue by thomasesr** [ElDavoo/wa-crypt-tools#79]
I have a perculiar problem, I have a backup on my Google drive that I am trying to restore, but it needs a 64 character string of characters to decrypt. And I don't have any copies of the string, or screenshots. However I do have my orginal encrypted_backup.key file from a oandbackup of the app (older) that I can use to decrypt my Google drive files. All I need is a util that does the inverse of creating a key file from the screenshot, I need to create the string from a key file. I don't know anything about programming and I looked everywhere how to extract (convert) it from the key file. I tried using the hexdump of the file but they are different lenghts. Can anyone help me?

**Comment by thomasesr** [comment]
Basically I need to do the inverse of this: 
` """Convert the key from a hex string to a java byte array"""`

**Comment by ElDavoo** [comment]
Try to decrypt anything with the verbose option activated and it should print out your key.
