### ISSUE TITLE
 Is there a way to get the key file by receiving the verification code through the whatsapp mobile phone number?

### ISSUE THREAD

**Issue by irainbw** [ElDavoo/wa-crypt-tools#80]
As the title says, I found that some software can verify the mobile phone before parsing the encrypted file. I guess that the key is obtained in this way, and then the encrypted file is parsed. How is this method implemented?

**Comment by ElDavoo** [comment]
By talking with the whatsapp servers.
This project does not want to talk with servers and is 100% offline.

Talking with servers without getting banned is very difficult
