### ISSUE TITLE
WA Business decrypt15

### ISSUE THREAD

**Issue by aviv926** [ElDavoo/wa-crypt-tools#82]
**Hexdump of your key file**
How to crate this Hexdump?

**Hexdump of the encrypted DB:**
How to crate this 256 Hexdump?

**Screenshots Program output using -v and -f**
 
![image](https://github.com/ElDavoo/wa-crypt-tools/assets/51673860/a9612605-503a-4b71-9592-abfeed3eac68)

**Additional context**
For whatever reason I can't extract a WhatsApp database that is end-to-end encrypted
I put the 64 character key
I use the **beta** version of WhatsApp Business
I tried with -f and it didn't work either
What do you think could be the problem?

**Comment by aviv926** [comment]
No problem, I just took a new backup with a new key and everything works as it should.

thanks for this amazing project

**Comment by ElDavoo** [comment]
As the program says, the backup is (was) corrupted.
I often have the same problem, caused by faulty USB cables and bad USB protocol (MTP really sucks!). That's why the program errors out if the data is not intact.

Thanks for telling me it works on WA business too!

**Comment by ElDavoo** [comment]
The program says the checksum is OK, so the data is intact, but the authentication failed, which means the key is wrong or does not match with the database.
Maybe that database backup was taken before you generated the new key?

Anyway, Thanks for telling me it works on WA business too!

**Comment by ElDavoo** [comment]
On Linux you use the CLI program hexdump.
On windows you can use HxD.
Anyway it's not needed anymore.

**Comment by aviv926** [comment]
> On Linux you use the CLI program hexdump. On windows you can use HxD. Anyway it's not needed anymore.

I saw the repeated comment just now
Thanks for your reply and as always thanks for this project

I thought you might want to integrate this project into your project or refer to this project

[https://github.com/ddz/whatsapp-media-decrypt
](https://github.com/ddz/whatsapp-media-decrypt
)
What do you think?

**Comment by ElDavoo** [comment]
> What do you think?  

Why should I do that?

**Comment by aviv926** [comment]
> > What do you think?  
> 
> Why should I do that?
> 
> 

Both of you deal with decrypting and encrypting files in the context of WhatsApp, I assume that whoever enters your project will find the project I linked useful to him as well.

**Comment by ElDavoo** [comment]
> in the context of WhatsApp

The context of whatsapp is too broad.  That projects decrypts encrypted media stored (temporarely) in whatsapp servers.  This project aims to decrypt local backups (and soon, cloud-downloaded projects - but it won't download files). So in a certain way these two projects are unrelated.

**Comment by aviv926** [comment]
I got you :) In fact, I was interested in understanding the understanding behind the encryption of WhatsApp, so your project and the project I linked were in context for me.
Anyway, thank you for this project !!!

By the way, can I ask if you created the project using an official WhatsApp document to understand the encryption algorithm?

**Comment by ElDavoo** [comment]
> , can I ask if you created the project using an official WhatsApp document

no, just guessing the file format and building on previous work
