### ISSUE TITLE
What if I deleted my whatsapp account and create a new one with the same number? Decryptable?

### ISSUE THREAD

**Issue by Emporea** [ElDavoo/wa-crypt-tools#89]
I am struggling to access an old crypt12 file that I backed up when I was younger and since then I have not had WhatsApp in between because I even deleted the account a few years ago.

I just have found the crypt12 backup file (and several crypt1 settings files) on an old drive and have created a new WhatsApp account with the same number but on a different phone that I no longer have. As expected, although I was very disappointed, my attempt to access it failed outright.

The required key is probably not the correct one because the phone and account have changed, even though the number is the same.

Is there a solution?
I ask for your help.

```
decrypt14_15 --force ./key ./msgstore.db.crypt12 ./msgstore.db
[I] Crypt12/14 key loaded
[E] WhatsApp version not found
[E] The phone number end is not 2 characters long
[E] Could not parse the IV from the protobuf message. Please report a bug.
[I] WhatsApp version not found (Crypt12?)
[F] Could not create a decryption cipher
```

**Comment by ElDavoo** [comment]
They probably have all of your keys in the server. I've documented up to 3 key versions. You can see which key version you have with `-v`.

**Comment by ElDavoo** [comment]
They probably have all of your keys in the server. I've documented up to 3 key versions. You can see which key version you have with `-v`.

Would you like to try with the development version and `-v` flag?

**Comment by kmontag** [comment]
@ElDavoo I'm running into a similar issue trying to restore an old crypt12 backup (though my account wasn't deleted in the meantime). Passing `-v` shows `key_version: 02`, and the program correctly identifies the last two digits of my phone number, but then fails with `Authentication tag mismatch: MAC check failed.`.

I don't think the backup is corrupt, so I suppose this must be a mismatch in the key version. Is the verdict that it's simply impossible to obtain other key versions from the WhatsApp servers?

**Comment by ElDavoo** [comment]
From what you described, it looks like that. I don't know the answer to these questions, I don't know how WA and its servers manage keys.

**Comment by kmontag** [comment]
Got it, thanks for the response.
