### ISSUE TITLE
I get msgstore.db parts in all options, only the file is 0 kb

### ISSUE THREAD

**Issue by sezerbulanik** [ElDavoo/wa-crypt-tools#94]
I get msgstore.db parts in all options, only the file is 0 kb
![sfsfsfs](https://github.com/ElDavoo/wa-crypt-tools/assets/59539850/e4490cea-07f2-4200-bab2-ea29b041e771)

**Comment by ElDavoo** [comment]
Logs?

**Comment by sezerbulanik** [comment]
I don't have much software knowledge, can you explain it a little more clearly, please?
![3333](https://github.com/ElDavoo/wa-crypt-tools/assets/59539850/f3f2fe79-adf4-42b0-95f8-f33b07cb9399)

**Comment by ElDavoo** [comment]
Run from the terminal

**Comment by sezerbulanik** [comment]
`Microsoft Windows [Version 10.0.22621.2428]
(c) Microsoft Corporation. Tüm hakları saklıdır.

C:\Users\sezerbulanik>git clone https://github.com/ElDavoo/WhatsApp-Crypt14-Crypt15-Decrypter.git
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\sezerbulanik>cd Desktop\WhatsApp-Crypt14-Crypt15-Decrypter

C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>python -m venv venv

C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>source venv/bin/activate
'source' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>.\venv\Scripts\activate.bat

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>.\venv\Scripts\Activate.ps1

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>python -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\sezerbulanik\desktop\whatsapp-crypt14-crypt15-decrypter\venv\lib\site-packages (23.3.1)

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>python -m pip install -r requirements.txt
Collecting javaobj-py3@ git+https://github.com/tcalmant/python-javaobj@fba64e9 (from -r requirements.txt (line 1))
  Cloning https://github.com/tcalmant/python-javaobj (to revision fba64e9) to c:\users\sezerbulanik\appdata\local\temp\pip-install-bxtw375g\javaobj-py3_d705b05258ba4bdb8c27d3c931132836
  ERROR: Error [WinError 2] Sistem belirtilen dosyayı bulamıyor while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>decrypt14_15.py [-h] [-f] [-nm] [-bs BUFFER_SIZE] [-ng] [-np]

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                       [-ivo IV_OFFSET] [-do DATA_OFFSET] [-v]
'[-ivo' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                       [keyfile] [encrypted] [decrypted]
'[keyfile]' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>
(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>Decrypts WhatsApp backup files encrypted with crypt12, 14 or 15
'Decrypts' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>
(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>positional arguments:
'positional' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  keyfile               The WhatsApp encrypted_backup key file or the hex
'keyfile' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        encoded key. Default: encrypted_backup.key
'encoded' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  encrypted             The encrypted crypt12, 14 or 15 file. Default:
'encrypted' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        msgstore.db.crypt15
'msgstore.db.crypt15' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  decrypted             The decrypted output file. Default: msgstore.db
'decrypted' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>
(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>options:
'options:' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  -h, --help            show this help message and exit
'-h' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  -f, --force           Makes errors non fatal. Default: false
'-f' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  -nm, --no-mem         Does not load files in RAM, stresses the disk more.
'-nm' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        Default: load files into RAM
'Default:' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  -bs BUFFER_SIZE, --buffer-size BUFFER_SIZE
'-bs' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        How many bytes of data to process at a time. Implies
'How' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        -nm. Default: 8192
'-nm.' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  -ng, --no-guess       Does not try to guess the offsets, only protobuf
'-ng' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        parsing.
'parsing.' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  -np, --no-protobuf    Does not try to parse the protobuf message, only
'-np' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        offset guessing.
'offset' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  -ivo IV_OFFSET, --iv-offset IV_OFFSET
'-ivo' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        The default offset of the IV in the encrypted file.
'The' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        Only relevant in offset guessing mode. Default: 8
'Only' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  -do DATA_OFFSET, --data-offset DATA_OFFSET
'-do' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        The default offset of the encrypted data in the
'The' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        encrypted file. Only relevant in offset guessing mode.
'encrypted' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>                        Default: 122
'Default:' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>  -v, --verbose         Prints all offsets and messages
'-v' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>python ./decrypt14_15.py ./key ./msgstore.db.crypt14 ./msgstore.db
[I] Crypt12/14 key loaded
[E] Could not import the proto classes: No module named 'proto.prefix_pb2'
To bypass checks, use the "--force" parameter

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>[I] Crypt12/14 key loaded
'[I]' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>[I] Database header parsed
'[I]' is not recognized as an internal or external command,
operable program or batch file.

(venv) C:\Users\sezerbulanik\Desktop\WhatsApp-Crypt14-Crypt15-Decrypter>[I] Done`

**Comment by ElDavoo** [comment]
Sorry you need to understand what you are doing

**Comment by ElDavoo** [comment]
You need to install git

**Comment by sezerbulanik** [comment]
Git Folder is already installed. I download from manual link

**Comment by sezerbulanik** [comment]
When I run the command -m pip install -r requirements.txt
Cannot find command 'git' - do you have 'git' installed and in your PATH? I get an error

**Comment by JSchimmelpfennig** [comment]
Then you don't have git installed.
You can install it for Windows from here: https://git-scm.com/download/win
