### ISSUE TITLE
Can't export my database.

### ISSUE THREAD

**Issue by picaso212** [ElDavoo/wa-crypt-tools#96]
Hello, I was able to decrypt my database msgstore.db.crypt15 to msgstore.db using the WhatsApp Crypt Tools script. However, when I try to read it in WhatsApp viewer or Wapa, it doesn't work.
![erreur](https://github.com/ElDavoo/wa-crypt-tools/assets/43498582/022b95dd-a099-4200-8730-1b1b12348e3c)

**Comment by ElDavoo** [comment]
open an issue in those projects then

**Comment by picaso212** [comment]
Hello ElDavoo,

I want to thank you for your "wa-crypt-tools" code, which allowed me to decrypt my WhatsApp Business database using Colab. This enables me to have a selective focus on my clients' messages.

I would like to know the most suitable method for exporting conversations to a CSV or Excel file.

Thank you so much; you've saved me three years of hard work.

**Comment by ElDavoo** [comment]
Thanks! It's not on the scope of this project to manipulate the decrypted files, but you should be able to use the WhatsApp-viewer's export functionality. You will need to dive in the issues section of that project to find a version or a patch that works on recent databases.

**Comment by picaso212** [comment]
Once again, I thank you immensely.
